# Generated by Django 2.1.5 on 2020-02-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='es_AI',
            field=models.BooleanField(default=False),
        ),
    ]
