# Generated by Django 2.1.5 on 2020-02-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_game_es_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ganador',
            field=models.IntegerField(default=0),
        ),
    ]
